// Copyright (c) 2023 Admenri. All rights reserved.
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=0b2e955d123a37f6995984e379956d0d425d762a$
//

#ifndef ACF_INCLUDE_CAPI_ACF_ENVIRONMENT_CAPI_H_
#define ACF_INCLUDE_CAPI_ACF_ENVIRONMENT_CAPI_H_
#pragma once

#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_request_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "include/capi/acf_response_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/internal/acf_def.h"
#include "include/internal/acf_scoped_refptr.h"
#include "include/internal/acf_string.h"
#include "include/internal/acf_types_wrappers.h"

#ifdef __cplusplus
extern "C" {
#endif

struct _acf_binary_value_t;
struct _acf_browser_handler_t;
struct _acf_browser_t;
struct _acf_cookie_t;
struct _acf_dictionary_value_t;
struct _acf_environment_t;
struct _acf_list_value_t;
struct _acf_post_data_element_t;
struct _acf_post_data_t;
struct _acf_profile_t;
struct _acf_request_t;
struct _acf_resource_request_handler_t;
struct _acf_response_t;
struct _acf_value_t;

///
/// Environment event handler
///
typedef struct _acf_environment_handler_t {
  ///
  /// Base structure.
  ///
  acf_base_ref_counted_t base;

  ///
  /// called when the environment has been initialized
  ///
  void(ACF_CALLBACK* on_initialized)(struct _acf_environment_handler_t* self,
                                     struct _acf_environment_t* env,
                                     int success);

  ///
  /// Called on the browser process IO thread before a resource request is
  /// initiated. The |browser| and |frame| values represent the source of the
  /// request. |request| represents the request contents and cannot be modified
  /// in this callback. |is_navigation| will be true (1) if the resource request
  /// is a navigation. |is_download| will be true (1) if the resource request is
  /// a download. |request_initiator| is the origin (scheme + domain) of the
  /// page that initiated the request. Set |disable_default_handling| to true
  /// (1) to disable default handling of the request, in which case it will need
  /// to be handled via acf_resource_request_handler_t::GetResourceHandler or it
  /// will be canceled. To allow the resource load to proceed with default
  /// handling return NULL. To specify a handler for the resource return a
  /// acf_resource_request_handler_t object. If this callback returns NULL the
  /// same function will be called on the associated
  /// acf_request_tContextHandler, if any.
  ///
  struct _acf_resource_request_handler_t*(
      ACF_CALLBACK* get_resource_request_handler)(
      struct _acf_environment_handler_t* self,
      struct _acf_profile_t* profile,
      int64 frame_id,
      struct _acf_request_t* request,
      int is_navigation,
      int is_download,
      const acf_string_t* request_initiator,
      int* block_request);
} acf_environment_handler_t;

///
/// ACF's environment which host a browser environment. A user data dir can
/// create a environment, Do not create environment on the same user data dir.
///
typedef struct _acf_environment_t {
  ///
  /// Base structure.
  ///
  acf_base_ref_counted_t base;

  ///
  /// Is same object
  ///
  int(ACF_CALLBACK* is_same)(struct _acf_environment_t* self,
                             struct _acf_environment_t* that);

  ///
  /// Get object remote ready
  ///
  int(ACF_CALLBACK* is_valid)(struct _acf_environment_t* self);

  ///
  /// Get Client Handler
  ///
  struct _acf_environment_handler_t*(ACF_CALLBACK* get_handler)(
      struct _acf_environment_t* self);

  ///
  /// Get ACF Components version
  ///
  // The resulting string must be freed by calling acf_string_userfree_free().
  acf_string_userfree_t(ACF_CALLBACK* get_browser_version)(
      struct _acf_environment_t* self);

  ///
  /// Get Browser Process PID
  ///
  uint64(ACF_CALLBACK* get_process_pid)(struct _acf_environment_t* self);

  ///
  /// Quit and wait for browser process return process exit code
  ///
  int(ACF_CALLBACK* terminate)(struct _acf_environment_t* self);

  ///
  /// Get default profile
  ///
  struct _acf_profile_t*(ACF_CALLBACK* get_default_profile)(
      struct _acf_environment_t* self);

  ///
  /// Create a profile hosted a user profile each path could only create a
  /// profile
  ///
  struct _acf_profile_t*(ACF_CALLBACK* create_profile)(
      struct _acf_environment_t* self,
      const acf_string_t* path,
      struct _acf_complete_handler_t* handler);

  ///
  /// Create browser from environment (async) return object immediately but the
  /// object was invalid.
  ///
  struct _acf_browser_t*(ACF_CALLBACK* create_browser)(
      struct _acf_environment_t* self,
      struct _acf_profile_t* profile,
      struct _acf_browser_handler_t* handler,
      const struct _acf_browser_create_params_t* params,
      struct _acf_dictionary_value_t* extra_info);
} acf_environment_t;

///
/// Init the acf context, this function must be called before any acf operation.
/// Method will create a thread to process the ipc message.
///
ACF_EXPORT int acf_environment_init_acfcontext(void);

///
/// Quit the acf context, call the function will destroy the connection with the
/// browser.
///
ACF_EXPORT int acf_environment_quit_acfcontext(void);

///
/// Create new environment on target user data dir
///
ACF_EXPORT acf_environment_t* acf_environment_create(
    const acf_string_t* browser_path,
    const struct _acf_environment_settings_t* settings,
    acf_environment_handler_t* handler);

///
/// Creates a new value object.
///
ACF_EXPORT struct _acf_value_t* acf_environment_create_value(void);

///
/// Creates a new object that is not owned by any other object. The specified
/// |data| will be copied.
///
ACF_EXPORT struct _acf_binary_value_t* acf_environment_create_binary(
    const void* data,
    size_t data_size);

///
/// Creates a new object that is not owned by any other object.
///
ACF_EXPORT struct _acf_dictionary_value_t* acf_environment_create_dictionary(
    void);

///
/// Creates a new object that is not owned by any other object.
///
ACF_EXPORT struct _acf_list_value_t* acf_environment_create_list(void);

///
/// Create a default cookie data.
///
ACF_EXPORT struct _acf_cookie_t* acf_environment_create_cookie(void);

///
/// Create a new CefRequest object.
///
ACF_EXPORT struct _acf_request_t* acf_environment_create_request(void);

///
/// Create a new CefPostData object.
///
ACF_EXPORT struct _acf_post_data_t* acf_environment_create_post_data(void);

///
/// Create a new acf_post_data_element_t object.
///
ACF_EXPORT struct _acf_post_data_element_t*
acf_environment_create_post_data_element(void);

///
/// Create a new acf_response_t object.
///
ACF_EXPORT struct _acf_response_t* acf_environment_create_response(void);

#ifdef __cplusplus
}
#endif

#endif  // ACF_INCLUDE_CAPI_ACF_ENVIRONMENT_CAPI_H_
