// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=a48cc50d42f13220b32267a8b656e58e638f0cfe$
//

#ifndef ACF_CTOCPP_CALLBACK_CTOCPP_H_
#define ACF_CTOCPP_CALLBACK_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfCallbackCToCpp : public AcfCToCppRefCounted<AcfCallbackCToCpp,
                                                     AcfCallback,
                                                     acf_callback_t> {
 public:
  AcfCallbackCToCpp();
  virtual ~AcfCallbackCToCpp();

  // AcfCallback methods.
  void Continue(bool cancel) override;
};

#endif  // ACF_CTOCPP_CALLBACK_CTOCPP_H_
