// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=9b5615769e223dd4415748b470687c05c3bc2e65$
//

#include "libacf_dll/ctocpp/resource_request_handler_ctocpp.h"
#include "libacf_dll/cpptoc/profile_cpptoc.h"
#include "libacf_dll/cpptoc/request_cpptoc.h"
#include "libacf_dll/cpptoc/response_cpptoc.h"
#include "libacf_dll/ctocpp/resource_handler_ctocpp.h"
#include "libacf_dll/ctocpp/response_filter_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

bool AcfResourceRequestHandlerCToCpp::OnBeforeResourceLoad(
    AcfRefPtr<AcfProfile> profile,
    int64 frame_id,
    AcfRefPtr<AcfRequest> request) {
  acf_resource_request_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, on_before_resource_load))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: profile; type: refptr_diff
  if (!profile.get())
    return false;
  // Verify param: request; type: refptr_diff
  if (!request.get())
    return false;

  // Execute
  int _retval = _struct->on_before_resource_load(
      _struct, AcfProfileCppToC::Wrap(profile), frame_id,
      AcfRequestCppToC::Wrap(request));

  // Return type: bool
  return _retval ? true : false;
}

AcfRefPtr<AcfResourceHandler>
AcfResourceRequestHandlerCToCpp::GetResourceHandler(
    AcfRefPtr<AcfProfile> profile,
    int64 frame_id,
    AcfRefPtr<AcfRequest> request) {
  acf_resource_request_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_resource_handler))
    return nullptr;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: profile; type: refptr_diff
  if (!profile.get())
    return nullptr;
  // Verify param: request; type: refptr_diff
  if (!request.get())
    return nullptr;

  // Execute
  acf_resource_handler_t* _retval =
      _struct->get_resource_handler(_struct, AcfProfileCppToC::Wrap(profile),
                                    frame_id, AcfRequestCppToC::Wrap(request));

  // Return type: refptr_same
  return AcfResourceHandlerCToCpp::Wrap(_retval);
}

void AcfResourceRequestHandlerCToCpp::OnResourceRedirect(
    AcfRefPtr<AcfProfile> profile,
    int64 frame_id,
    AcfRefPtr<AcfRequest> request,
    AcfRefPtr<AcfResponse> response,
    AcfString& new_url) {
  acf_resource_request_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, on_resource_redirect))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: profile; type: refptr_diff
  if (!profile.get())
    return;
  // Verify param: request; type: refptr_diff
  if (!request.get())
    return;
  // Verify param: response; type: refptr_diff
  if (!response.get())
    return;

  // Execute
  _struct->on_resource_redirect(_struct, AcfProfileCppToC::Wrap(profile),
                                frame_id, AcfRequestCppToC::Wrap(request),
                                AcfResponseCppToC::Wrap(response),
                                new_url.GetWritableStruct());
}

void AcfResourceRequestHandlerCToCpp::OnResourceResponse(
    AcfRefPtr<AcfProfile> profile,
    int64 frame_id,
    AcfRefPtr<AcfRequest> request,
    AcfRefPtr<AcfResponse> response) {
  acf_resource_request_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, on_resource_response))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: profile; type: refptr_diff
  if (!profile.get())
    return;
  // Verify param: request; type: refptr_diff
  if (!request.get())
    return;
  // Verify param: response; type: refptr_diff
  if (!response.get())
    return;

  // Execute
  _struct->on_resource_response(_struct, AcfProfileCppToC::Wrap(profile),
                                frame_id, AcfRequestCppToC::Wrap(request),
                                AcfResponseCppToC::Wrap(response));
}

AcfRefPtr<AcfResponseFilter>
AcfResourceRequestHandlerCToCpp::GetResourceResponseFilter(
    AcfRefPtr<AcfProfile> profile,
    int64 frame_id,
    AcfRefPtr<AcfRequest> request,
    AcfRefPtr<AcfResponse> response) {
  acf_resource_request_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, get_resource_response_filter))
    return nullptr;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: profile; type: refptr_diff
  if (!profile.get())
    return nullptr;
  // Verify param: request; type: refptr_diff
  if (!request.get())
    return nullptr;
  // Verify param: response; type: refptr_diff
  if (!response.get())
    return nullptr;

  // Execute
  acf_response_filter_t* _retval = _struct->get_resource_response_filter(
      _struct, AcfProfileCppToC::Wrap(profile), frame_id,
      AcfRequestCppToC::Wrap(request), AcfResponseCppToC::Wrap(response));

  // Return type: refptr_same
  return AcfResponseFilterCToCpp::Wrap(_retval);
}

void AcfResourceRequestHandlerCToCpp::OnResourceLoadComplete(
    AcfRefPtr<AcfProfile> profile,
    int64 frame_id,
    AcfRefPtr<AcfRequest> request,
    AcfRefPtr<AcfResponse> response,
    URLRequestStatus status,
    int64 received_content_length) {
  acf_resource_request_handler_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, on_resource_load_complete))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: profile; type: refptr_diff
  if (!profile.get())
    return;
  // Verify param: request; type: refptr_diff
  if (!request.get())
    return;
  // Verify param: response; type: refptr_diff
  if (!response.get())
    return;

  // Execute
  _struct->on_resource_load_complete(_struct, AcfProfileCppToC::Wrap(profile),
                                     frame_id, AcfRequestCppToC::Wrap(request),
                                     AcfResponseCppToC::Wrap(response), status,
                                     received_content_length);
}

// CONSTRUCTOR - Do not edit by hand.

AcfResourceRequestHandlerCToCpp::AcfResourceRequestHandlerCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfResourceRequestHandlerCToCpp::~AcfResourceRequestHandlerCToCpp() {}

template <>
acf_resource_request_handler_t* AcfCToCppRefCounted<
    AcfResourceRequestHandlerCToCpp,
    AcfResourceRequestHandler,
    acf_resource_request_handler_t>::UnwrapDerived(AcfWrapperType type,
                                                   AcfResourceRequestHandler*
                                                       c) {
  return nullptr;
}

template <>
AcfWrapperType
    AcfCToCppRefCounted<AcfResourceRequestHandlerCToCpp,
                        AcfResourceRequestHandler,
                        acf_resource_request_handler_t>::kWrapperType =
        WT_RESOURCE_REQUEST_HANDLER;
