// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f0161dca1beaaf3683b19faf9d48d57c7fcbc8b5$
//

#ifndef ACF_CTOCPP_RESOURCE_REQUEST_HANDLER_CTOCPP_H_
#define ACF_CTOCPP_RESOURCE_REQUEST_HANDLER_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_frame.h"
#include "include/acf_resource_request_handler.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class AcfResourceRequestHandlerCToCpp
    : public AcfCToCppRefCounted<AcfResourceRequestHandlerCToCpp,
                                 AcfResourceRequestHandler,
                                 acf_resource_request_handler_t> {
 public:
  AcfResourceRequestHandlerCToCpp();
  virtual ~AcfResourceRequestHandlerCToCpp();

  // AcfResourceRequestHandler methods.
  bool OnBeforeResourceLoad(AcfRefPtr<AcfProfile> profile,
                            int64 frame_id,
                            AcfRefPtr<AcfRequest> request) override;
  AcfRefPtr<AcfResourceHandler> GetResourceHandler(
      AcfRefPtr<AcfProfile> profile,
      int64 frame_id,
      AcfRefPtr<AcfRequest> request) override;
  void OnResourceRedirect(AcfRefPtr<AcfProfile> profile,
                          int64 frame_id,
                          AcfRefPtr<AcfRequest> request,
                          AcfRefPtr<AcfResponse> response,
                          AcfString& new_url) override;
  void OnResourceResponse(AcfRefPtr<AcfProfile> profile,
                          int64 frame_id,
                          AcfRefPtr<AcfRequest> request,
                          AcfRefPtr<AcfResponse> response) override;
  AcfRefPtr<AcfResponseFilter> GetResourceResponseFilter(
      AcfRefPtr<AcfProfile> profile,
      int64 frame_id,
      AcfRefPtr<AcfRequest> request,
      AcfRefPtr<AcfResponse> response) override;
  void OnResourceLoadComplete(AcfRefPtr<AcfProfile> profile,
                              int64 frame_id,
                              AcfRefPtr<AcfRequest> request,
                              AcfRefPtr<AcfResponse> response,
                              URLRequestStatus status,
                              int64 received_content_length) override;
};

#endif  // ACF_CTOCPP_RESOURCE_REQUEST_HANDLER_CTOCPP_H_
