// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e2e8be6c0f07b9b37252df7146128c61b184a6c8$
//

#ifndef ACF_CTOCPP_RESPONSE_FILTER_CTOCPP_H_
#define ACF_CTOCPP_RESPONSE_FILTER_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_frame.h"
#include "include/acf_resource_request_handler.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class AcfResponseFilterCToCpp
    : public AcfCToCppRefCounted<AcfResponseFilterCToCpp,
                                 AcfResponseFilter,
                                 acf_response_filter_t> {
 public:
  AcfResponseFilterCToCpp();
  virtual ~AcfResponseFilterCToCpp();

  // AcfResponseFilter methods.
  bool InitFilter() override;
  FilterStatus Filter(void* data_in,
                      size_t data_in_size,
                      size_t& data_in_read,
                      void* data_out,
                      size_t data_out_size,
                      size_t& data_out_written) override;
};

#endif  // ACF_CTOCPP_RESPONSE_FILTER_CTOCPP_H_
