// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=8e792e14b0303193ad7191956340582d102fa66e$
//

#ifndef ACF_CPPTOC_CALLBACK_CPPTOC_H_
#define ACF_CPPTOC_CALLBACK_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfCallbackCppToC : public AcfCppToCRefCounted<AcfCallbackCppToC,
                                                     AcfCallback,
                                                     acf_callback_t> {
 public:
  AcfCallbackCppToC();
  virtual ~AcfCallbackCppToC();
};

#endif  // ACF_CPPTOC_CALLBACK_CPPTOC_H_
