// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=bfd5b4aee3d4fe6ea6674387eed4c8e2740516b5$
//

#ifndef ACF_CPPTOC_ENVIRONMENT_CPPTOC_H_
#define ACF_CPPTOC_ENVIRONMENT_CPPTOC_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_browser_handler.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_request.h"
#include "include/acf_resource_request_handler.h"
#include "include/acf_response.h"
#include "include/acf_values.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_browser_handler_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_request_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "include/capi/acf_response_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfEnvironmentCppToC : public AcfCppToCRefCounted<AcfEnvironmentCppToC,
                                                        AcfEnvironment,
                                                        acf_environment_t> {
 public:
  AcfEnvironmentCppToC();
  virtual ~AcfEnvironmentCppToC();
};

#endif  // ACF_CPPTOC_ENVIRONMENT_CPPTOC_H_
