// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b6eb8d0016b0a59f9660c5aaa7bd0613aa2a2652$
//

#ifndef ACF_CPPTOC_POST_DATA_CPPTOC_H_
#define ACF_CPPTOC_POST_DATA_CPPTOC_H_
#pragma once

#include "include/acf_request.h"
#include "include/capi/acf_request_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfPostDataCppToC : public AcfCppToCRefCounted<AcfPostDataCppToC,
                                                     AcfPostData,
                                                     acf_post_data_t> {
 public:
  AcfPostDataCppToC();
  virtual ~AcfPostDataCppToC();
};

#endif  // ACF_CPPTOC_POST_DATA_CPPTOC_H_
