// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=72be40738dedcddcf68cb0617d624d2781239cbf$
//

#ifndef ACF_CPPTOC_POST_DATA_ELEMENT_CPPTOC_H_
#define ACF_CPPTOC_POST_DATA_ELEMENT_CPPTOC_H_
#pragma once

#include "include/acf_request.h"
#include "include/capi/acf_request_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfPostDataElementCppToC
    : public AcfCppToCRefCounted<AcfPostDataElementCppToC,
                                 AcfPostDataElement,
                                 acf_post_data_element_t> {
 public:
  AcfPostDataElementCppToC();
  virtual ~AcfPostDataElementCppToC();
};

#endif  // ACF_CPPTOC_POST_DATA_ELEMENT_CPPTOC_H_
