// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=6e5cc8de8dd18d0b32a030139cf6ff196f5df90d$
//

#ifndef ACF_CPPTOC_REQUEST_CPPTOC_H_
#define ACF_CPPTOC_REQUEST_CPPTOC_H_
#pragma once

#include "include/acf_request.h"
#include "include/capi/acf_request_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfRequestCppToC
    : public AcfCppToCRefCounted<AcfRequestCppToC, AcfRequest, acf_request_t> {
 public:
  AcfRequestCppToC();
  virtual ~AcfRequestCppToC();
};

#endif  // ACF_CPPTOC_REQUEST_CPPTOC_H_
