// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=4e0f8928f103cbdcdccbde3041375403f6a901df$
//

#include "libacf_dll/cpptoc/resource_skip_callback_cpptoc.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void ACF_CALLBACK
resource_skip_callback_cont(struct _acf_resource_skip_callback_t* self,
                            int64 bytes_skipped) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self)
    return;

  // Execute
  AcfResourceSkipCallbackCppToC::Get(self)->Continue(bytes_skipped);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

AcfResourceSkipCallbackCppToC::AcfResourceSkipCallbackCppToC() {
  GetStruct()->cont = resource_skip_callback_cont;
}

// DESTRUCTOR - Do not edit by hand.

AcfResourceSkipCallbackCppToC::~AcfResourceSkipCallbackCppToC() {}

template <>
AcfRefPtr<AcfResourceSkipCallback> AcfCppToCRefCounted<
    AcfResourceSkipCallbackCppToC,
    AcfResourceSkipCallback,
    acf_resource_skip_callback_t>::UnwrapDerived(AcfWrapperType type,
                                                 acf_resource_skip_callback_t*
                                                     s) {
  return nullptr;
}

template <>
AcfWrapperType AcfCppToCRefCounted<AcfResourceSkipCallbackCppToC,
                                   AcfResourceSkipCallback,
                                   acf_resource_skip_callback_t>::kWrapperType =
    WT_RESOURCE_SKIP_CALLBACK;
