// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=80f0a26c33eeaeeae06bfd43b52c22552f4b55b5$
//

#ifndef ACF_CPPTOC_RESOURCE_REQUEST_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_RESOURCE_REQUEST_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_frame.h"
#include "include/acf_resource_request_handler.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfResourceRequestHandlerCppToC
    : public AcfCppToCRefCounted<AcfResourceRequestHandlerCppToC,
                                 AcfResourceRequestHandler,
                                 acf_resource_request_handler_t> {
 public:
  AcfResourceRequestHandlerCppToC();
  virtual ~AcfResourceRequestHandlerCppToC();
};

#endif  // ACF_CPPTOC_RESOURCE_REQUEST_HANDLER_CPPTOC_H_
