// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=dd6617772aaef55769e310801941cccfdd3f8ffc$
//

#ifndef ACF_CPPTOC_RESPONSE_CPPTOC_H_
#define ACF_CPPTOC_RESPONSE_CPPTOC_H_
#pragma once

#include "include/acf_response.h"
#include "include/capi/acf_response_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class AcfResponseCppToC : public AcfCppToCRefCounted<AcfResponseCppToC,
                                                     AcfResponse,
                                                     acf_response_t> {
 public:
  AcfResponseCppToC();
  virtual ~AcfResponseCppToC();
};

#endif  // ACF_CPPTOC_RESPONSE_CPPTOC_H_
