// Copyright (c) 2023 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7da99209b01f2b8ac73e686b02e13ace41384478$
//

#ifndef ACF_WRAPPER_TYPES_H_
#define ACF_WRAPPER_TYPES_H_
#pragma once

enum AcfWrapperType {
  WT_BASE_REF_COUNTED = 1,
  WT_BASE_SCOPED,
  WT_BINARY_VALUE,
  WT_BROWSER,
  WT_BROWSER_HANDLER,
  WT_CALLBACK,
  WT_COMPLETE_HANDLER,
  WT_COMPLETE_VALUE_HANDLER,
  WT_CONTEXT_MENU_CALLBACK,
  WT_CONTEXT_MENU_MODEL,
  WT_CONTEXT_MENU_PARAMS,
  WT_COOKIE,
  WT_COOKIE_MANAGER,
  WT_COOKIE_VISITOR,
  WT_COOKIES_GETTER,
  WT_DICTIONARY_VALUE,
  WT_ENVIRONMENT,
  WT_ENVIRONMENT_HANDLER,
  WT_FRAME,
  WT_LIST_VALUE,
  WT_LOGIN_DELEGATE,
  WT_NEW_WINDOW_DELEGATE,
  WT_NUMBER_COMPLETE_HANDLER,
  WT_POST_DATA,
  WT_POST_DATA_ELEMENT,
  WT_PROFILE,
  WT_REQUEST,
  WT_RESOURCE_HANDLER,
  WT_RESOURCE_READ_CALLBACK,
  WT_RESOURCE_REQUEST_HANDLER,
  WT_RESOURCE_SKIP_CALLBACK,
  WT_RESPONSE,
  WT_RESPONSE_FILTER,
  WT_STRING_VISITOR,
  WT_VALUE,

  WT_LAST
};

#endif  // ACF_WRAPPER_TYPES_H_
